# TravelTurkey - CI/CD Configuration
# GitHub Actions workflow for React Native CLI project

name: TravelTurkey CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript check
        run: npm run type-check

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          fail_ci_if_error: true

  build-android:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install dependencies
        run: npm ci

      - name: Clean project
        run: npm run clean

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk

  performance-audit:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Bundle size check
        run: |
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android-bundle.js \
            --assets-dest assets/

          # Check bundle size (should be < 2MB for good performance)
          BUNDLE_SIZE=$(wc -c < android-bundle.js)
          echo "Bundle size: $BUNDLE_SIZE bytes"

          if [ $BUNDLE_SIZE -gt 2097152 ]; then
            echo "❌ Bundle size too large: $BUNDLE_SIZE bytes (> 2MB)"
            exit 1
          else
            echo "✅ Bundle size OK: $BUNDLE_SIZE bytes"
          fi

      - name: Check for performance regressions
        run: |
          # Run performance tests if they exist
          if [ -f "__tests__/performance/performance.test.js" ]; then
            npm run test:performance
          fi
